### ISSUE TITLE
Code correctness

### ISSUE THREAD

**Issue by Ved548** [Saroopashree/openmp-kmeans#1]
Hi,

I was just going through your parallel code for kmeans

It gives me seg-fault. Is the code correctly implemented? I see the functionality is aberrant. 
Can you let me know how you verified the correctness?

**Comment by Saroopashree** [comment]
Hi @Ved548 ,
This code worked for me. The OS that I worked with is MacOS 10.14 (Catalina).
Please, check if your problem is anywhere related to the OS that you use.

If the problem is not the OS, then please help us find the error in the code :slightly_smiling_face:
